branches:
  only:
  - master
  - "/^reverse-proxy-auth-sonar-plugin-.+$/"
language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
addons:
  apt:
    packages:
    - graphviz
  sonarqube: true
env:
  global:
  - secure: gYebEQVY4X8W9aLkZCLkVgtL8tPmW3MsVartw4Q68DMGGGxQagzMOu/QhfjD0qB4QeTdIP7k5M4ye/Y37d/RZGwr0oNg9EX0h6OKAhhQRRXioO+9eEraSl7fYz7kKYxVnuaoEziFagVLrQvX43bom3F7+sKQBtMixN2V9ip/sLA=
  - secure: HMB/tw3WtFBms6p1cYm1WFvMX9Owt0QF8Sxdah7LZlQGvD3QWgbrfKu4EcGtrseWwQrhIl7MuhDVUA2M4Rsp5wdQPItJ3R7ZQrNBZpgiqPUCPARltUNuvXNr+QYod8giuPi0okN/93E6iqcQP/4h9MP0EZ3LCEexZFYsYzIfbdc=
install:
- mvn dependency:go-offline
before_script:
- mvn clean
- if [ ${TRAVIS_TAG} ]; then echo scm.tag=${TRAVIS_TAG} > release.properties ; echo
  scm.url=scm:git:https://github.com/${TRAVIS_REPO_SLUG} >> release.properties ; fi
script:
- if [ ! ${TRAVIS_TAG} ]; then mvn install site ; else mvn release:perform ; fi
after_success:
- mvn sonar:sonar
before_install:
- openssl aes-256-cbc -K $encrypted_7560bbc32cbd_key -iv $encrypted_7560bbc32cbd_iv
  -in deploy-keys.tar.enc -out deploy-keys.tar -d
- tar xf deploy-keys.tar -C $HOME && chmod go-rwx -R .m2 .ssh
deploy:
- provider: script
  script: mvn deploy site-deploy
  on: 
    branch: master

